name: Build

on:
   workflow_dispatch:

jobs:
  build-tweak:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1

      - name: Build packages
        run: |
          export PATH="$(brew --prefix make)/libexec/gnubin:$PATH"
          export THEOS="${{ github.workspace }}/theos"
          rm -rf packages && make clean && make package FINALPACKAGE=1 && make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: "package"
          path: ${{ github.workspace }}/packages/*-arm.deb

      - name: Upload rootless package
        uses: actions/upload-artifact@v4
        with:
          name: "rootless package"
          path: ${{ github.workspace }}/packages/*-arm64.deb
